# This workflow will generate the documentations of the various modules present into the docs/ directory.

name: Make documentations

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  write:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set distribution release  #@noliarn https://github.com/nektos/act/issues/251#issuecomment-706412948
        run: |
          if [ ! -f "/etc/lsb-release" ]; then echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release; fi

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install pdoc3 0.9.1 if not installed
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3==0.9.1
          echo "Generating documentation in docs/ directory"

      - name: Creates documentations
        run: |
          pdoc --html `ls -d */ | grep -v -e 'venv' -e 'docs' -e 'pycache'` -o docs/ --force
